window.projectDetails = {
  samsung: {
    eyebrow: "Industry research · Samsung Electronics · Jun 2024–Mar 2025",
    title: "Screen Multimodal Interaction Research",
    summary: "A research program translating evidence from 11 commercial products, academic literature, and planned experiments into context-aware voice, gesture, and touch interaction guidelines.",
    role: "Took primary responsibility for designing experiments that evaluated multimodal interaction techniques for TV display experiences, supported by product mapping and computational media analysis.",
    methods: "Cross-product feature mapping; YouTube crawling; multilingual preprocessing; KoBERTopic; literature review; 2×2 and mixed-design experiment planning.",
    finding: "The work reframed multimodal interaction as a context-dependent system problem: input timing, feedback, personalization, environment, and device embodiment need to be designed together.",
    image: "assets/detail/samsung/thumbnail.png",
    links: [{ label: "Research deck ↗", url: "https://docs.google.com/presentation/d/18RPXCjuIdNgSbMqGeFMbLbEkKm9YN6Qu/edit" }],
    caseStudy: {
      meta: ["Jun 2024–Mar 2025", "Samsung Electronics", "Sogang University × Sungkyunkwan University", "₩100M + VAT"],
      map: [
        { label: "Question", title: "When should screens listen, watch, or wait?" },
        { label: "Landscape", title: "Map device embodiments and interaction patterns" },
        { label: "Data", title: "Read 11 products through user-generated video" },
        { label: "Studies", title: "Turn patterns into testable design questions" },
        { label: "Guidelines", title: "Connect modality to real context" },
      ],
      role: {
        title: "I took primary responsibility for turning the landscape into experiments.",
        body: "I designed experiments evaluating multimodal interaction techniques for TV display experiences. Product taxonomy, YouTube data collection, KoBERTopic, and literature synthesis gave me the evidence base to define variables, conditions, and context-sensitive interaction questions rather than treating voice, gesture, and touch as isolated features.",
        tags: ["Experiment design", "TV interaction", "Multimodal systems", "KoBERTopic", "Evidence synthesis"],
      },
      sections: [
        {
          key: "question",
          label: "01 · The question",
          title: "A voice command that feels natural on a phone can feel awkward on a wall-sized screen.",
          paragraphs: [
            "The project began with a deceptively simple problem: screens now vary from personal mobile devices to shared TVs and body-adjacent displays, yet multimodal interfaces are often designed as if the same voice, gesture, and touch rules apply everywhere.",
            "We asked how device embodiment, social setting, distance, and task should change when a system initiates a prompt, accepts input, and returns feedback.",
          ],
          alt: "Samsung Electronics screen multimodal interaction research",
          caption: "The study organized screen systems by embodiment before comparing their interaction patterns.",
        },
        {
          key: "landscape",
          label: "02 · Product landscape",
          title: "We built a common vocabulary across products that were difficult to compare.",
          paragraphs: [
            "The team classified devices and features across four dimensions: input modality, output and feedback, environmental context, and user or social configuration. This made it possible to compare products whose marketing language and feature labels were otherwise inconsistent.",
            "The classification step was not just cataloguing. It exposed which interaction decisions repeatedly appeared together and where commercial products left gaps that experiments could address.",
          ],
          image: "assets/detail/samsung/product-map.png",
          alt: "Product classification and multimodal interaction feature map",
          caption: "A shared feature map turned a fragmented product space into comparable interaction evidence.",
        },
        {
          key: "data",
          label: "03 · Data and analysis",
          title: "Eleven products became a multilingual corpus of real use, explanation, and friction.",
          paragraphs: [
            "I helped crawl YouTube data around 11 screen-based products and prepare multilingual video metadata and transcripts for analysis. After cleaning and normalization, we used KoBERTopic to surface recurring themes in how products were demonstrated and discussed.",
            "I then interpreted topics against product features and use contexts, so the output was not a list of clusters but an account of what users expected, where interactions broke down, and which contexts mattered.",
          ],
          visual: { kicker: "Analysis pipeline", title: "From videos to design evidence", items: ["Collect product-centered YouTube data", "Clean multilingual text and metadata", "Model themes with KoBERTopic", "Interpret topics against device context"] },
          caption: "My primary technical work joined collection, preprocessing, topic modeling, and qualitative interpretation.",
        },
        {
          key: "studies",
          label: "04 · Experimental roadmap",
          title: "Patterns from the landscape were converted into controlled HCI studies.",
          paragraphs: [
            "I took primary responsibility for designing experiments on when voice agents should appear, where feedback should be placed, and how timing interacts with task and distance. For smart-TV voice interaction, I helped formalize a 2×2 framing around timing and position.",
            "These studies were planned to distinguish visibility from interruption, convenience from privacy, and modality availability from actual appropriateness. They should be read as an experimental roadmap rather than completed outcome claims.",
          ],
          image: "assets/detail/samsung/experiment-plan.png",
          alt: "Planned multimodal interaction experiments",
          caption: "The research translated descriptive patterns into variables that could be experimentally isolated.",
        },
        {
          key: "guidelines",
          label: "05 · Design implication",
          title: "Multimodal guidance should specify not only what input is possible, but when it is appropriate.",
          paragraphs: [
            "The emerging framework treats input timing, feedback, personalization, environment, and embodiment as linked decisions. A system should not merely expose every modality; it should select and coordinate them according to context.",
            "For me, the project was a bridge between informatics and interaction design: large-scale media traces helped identify where controlled studies and concrete product guidelines were most needed.",
          ],
          visual: { kicker: "Guideline spine", title: "Five linked decisions", items: ["Timing", "Feedback", "Personalization", "Environment", "Embodiment"] },
          caption: "The contribution is a context-dependent guideline structure rather than a universal hierarchy of modalities.",
        },
      ],
      outcome: {
        label: "What this work demonstrates",
        title: "I can turn a broad technology landscape into precise experimental questions.",
        body: "The project shows the technical side of my research practice without separating it from human context: I used product evidence, crawling, topic modeling, and literature synthesis to design controlled studies of when multimodal TV interaction is actually appropriate.",
      },
    },
  },

  nhis: {
    eyebrow: "Public-sector research · National Health Insurance Service",
    title: "Media & Social Media Issue Analysis on National Health Insurance",
    summary: "A recurring quarterly project tracking how the National Health Insurance Service was framed across news and online media, then translating those traces into actionable issue narratives.",
    role: "Research assistant responsible for news crawling across 10 major Korean outlets and for analysis, interpretation, and report development.",
    methods: "Python scraping; Korean NLP preprocessing; TF-IDF; semantic co-occurrence networks; KoBERTopic/LDA; cross-outlet and time-series comparison.",
    finding: "Quarterly reports connected keyword and topic patterns to policy events, public concerns, and strategic communication implications.",
    image: "assets/detail/nhis/thumbnail.png",
    caseStudy: {
      meta: ["Quarterly research", "NHIS client project", "10 news outlets", "News + video + social data"],
      map: [
        { label: "Need", title: "See public issues before they harden" },
        { label: "Collect", title: "Build a repeatable media corpus" },
        { label: "Analyze", title: "Find salience, structure, and latent topics" },
        { label: "Interpret", title: "Reconnect output to policy events" },
        { label: "Report", title: "Deliver quarterly communication insight" },
      ],
      role: {
        title: "I owned the news-data lane and stayed involved through interpretation.",
        body: "I built and ran collection workflows for 10 major Korean press outlets, participated in preprocessing and quantitative analysis, and helped translate model outputs into issue narratives for the client-facing quarterly reports.",
        tags: ["Python scraping", "Korean NLP", "TF-IDF", "Semantic networks", "Topic modeling", "Policy interpretation"],
      },
      sections: [
        {
          key: "need",
          label: "01 · The need",
          title: "For a public institution, issue detection is not the same as counting mentions.",
          paragraphs: [
            "The project tracked how the NHIS was portrayed across rapidly changing media cycles. The practical question was which concerns were emerging, how their framing differed by outlet, and what those shifts meant for public communication.",
            "That required a recurring method: every quarter had to remain comparable while still being sensitive to new policy events and unexpected controversies.",
          ],
          alt: "National Health Insurance Service media issue analysis",
          caption: "The analytical target was issue structure and meaning, not raw volume alone.",
        },
        {
          key: "collect",
          label: "02 · Collection",
          title: "I built a consistent news corpus across 10 major Korean outlets.",
          paragraphs: [
            "I developed and ran keyword-based scraping workflows to collect article titles, dates, sources, and full text. The wider project also incorporated YouTube metadata, comments, social media, and online communities.",
            "Consistent fields and quarter-level archives made it possible to compare sources and time windows without losing the context of individual news cycles.",
          ],
          visual: { kicker: "Data sources", title: "A multi-channel issue corpus", items: ["10 major press outlets — my primary domain", "YouTube videos and comments", "Social media and online communities"] },
          caption: "My central responsibility was the press corpus, integrated into a broader media-monitoring project.",
        },
        {
          key: "analyze",
          label: "03 · Computational pipeline",
          title: "Each method answered a different question about the same public conversation.",
          paragraphs: [
            "After Korean tokenization, stopword removal, and noise filtering, TF-IDF identified terms that were unusually salient by source and period. Co-occurrence networks exposed how those terms clustered, while KoBERTopic and LDA surfaced broader latent themes.",
            "Using multiple methods reduced the temptation to treat one ranking or model as the whole story. Agreement and disagreement among outputs became evidence for closer interpretation.",
          ],
          visual: { kicker: "Method stack", title: "From raw articles to issue structure", items: ["Preprocess Korean text", "Rank salience with TF-IDF", "Map semantic co-occurrence", "Model topics with KoBERTopic / LDA"] },
          caption: "The pipeline combined interpretable lexical measures with relational and latent-topic views.",
        },
        {
          key: "interpret",
          label: "04 · Interpretation",
          title: "Models found patterns; our job was to explain why they mattered now.",
          paragraphs: [
            "I contributed to qualitative synthesis that reconnected clusters and topic distributions to policy announcements, news cycles, and differences in outlet framing. This step prevented technical outputs from becoming decontextualized dashboards.",
            "The recurring analysis tracked concerns such as premium policy, coverage scope, and institutional trust while distinguishing a temporary spike from a durable shift in discourse.",
          ],
          visual: { kicker: "Analytical outputs", title: "Evidence assembled for judgment", items: ["Keyword rankings", "Semantic network graphs", "Topic distributions", "Cross-outlet framing comparison"] },
          caption: "Interpretation joined quantitative traces to the institutional and policy context in which they appeared.",
        },
        {
          key: "report",
          label: "05 · Deliverable",
          title: "The final product was a decision-ready quarterly account, not an exploratory notebook.",
          paragraphs: [
            "Each report brought together an issue summary, keyword trends, network visualizations, topic-model findings, and strategic communication implications. The recurring cadence demanded both technical repeatability and clear narrative structure.",
            "This experience taught me to treat data work as a chain of accountability: collection choices shape models, models shape interpretations, and interpretations can influence public communication.",
          ],
          visual: { kicker: "Quarterly report", title: "Five client-facing layers", items: ["Issue summary", "Keyword trend", "Network structure", "Topic movement", "Communication implication"] },
          caption: "The deliverable translated analytical complexity into a stable structure the client could revisit each quarter.",
        },
      ],
      outcome: {
        label: "What this work demonstrates",
        title: "Applied informatics with policy context and communication responsibility.",
        body: "I did not stop at collecting and modeling text. I learned to explain what each method could and could not support, connect patterns to public events, and write toward decisions made by a real institution.",
      },
    },
  },

  "missionary-film": {
    eyebrow: "Independent production · In progress",
    title: "Missionary Film: An AI + Game Engine Production Pipeline",
    summary: "A short historical film using original screenwriting, AI-generated visual assets, and Unreal Engine MetaHumans to explore a production model beyond conventional location and casting constraints.",
    role: "Writer, director, and producer.",
    methods: "Unreal Engine 5; MetaHuman Creator; Lumen; Sequencer; Midjourney/Stable Diffusion; texture and lighting refinement; editing and audio design.",
    finding: "The project treats generative AI and real-time engines as a coherent filmmaking workflow rather than isolated effects tools.",
    image: "assets/detail/missionary-film/image.png",
    caseStudy: {
      meta: ["Independent film", "In progress", "Original screenplay", "AI + Unreal Engine 5"],
      map: [
        { label: "Story", title: "Begin with historical responsibility" },
        { label: "Characters", title: "Build expressive digital humans" },
        { label: "World", title: "Generate and refine scene assets" },
        { label: "Cinema", title: "Stage, light, and render in UE5" },
        { label: "Question", title: "Test a new independent pipeline" },
      ],
      role: {
        title: "Writer, director, and producer.",
        body: "I wrote the original screenplay and lead the creative and technical production pipeline: narrative structure, character and scene development, MetaHuman work, visual generation and refinement, virtual cinematography, editing, and sound.",
        tags: ["Screenwriting", "Directing", "MetaHuman", "Unreal Engine 5", "Generative visuals", "Post-production"],
      },
      sections: [
        {
          key: "story",
          label: "01 · Story first",
          title: "The technology only matters if the historical people remain more than visual demonstrations.",
          paragraphs: [
            "The project began as an original screenplay about missionary history. I developed the narrative structure, dialogue, and scene plan before choosing tools, because the ethical and emotional stakes of depicting real figures cannot be delegated to a visual pipeline.",
            "Research and writing define what must remain specific; production technology is used to make those scenes possible at an independent scale.",
          ],
          alt: "Missionary film visual development triptych",
          caption: "Early visual development studies a historical figure through source material, generated imagery, and character direction.",
        },
        {
          key: "characters",
          label: "02 · Digital humans",
          title: "MetaHuman makes a performer possible, but performance still has to be directed.",
          paragraphs: [
            "I use MetaHuman Creator to build photorealistic characters and then refine appearance, expression, staging, and shot continuity inside Unreal Engine 5. The goal is not a generic digital double but a character who can carry a scene.",
            "This part of the process combines technical iteration with familiar directing questions: where a character looks, how long a reaction lasts, and what the camera should withhold.",
          ],
          visual: { kicker: "Character pipeline", title: "From identity to performance", items: ["Historical reference", "MetaHuman build", "Expression and motion", "Shot-level direction"] },
          caption: "Digital-human quality depends on performance and cinematic context, not facial realism alone.",
        },
        {
          key: "world",
          label: "03 · Generative world-building",
          title: "AI-generated imagery is treated as raw production material, not a finished frame.",
          paragraphs: [
            "Backgrounds and scene assets are generated with tools such as Midjourney and Stable Diffusion, then selected and reworked for historical coherence, texture quality, lighting, and continuity.",
            "The important labor happens after generation: removing visual inconsistencies, aligning perspective and palette, and preparing assets to live within the same cinematic world.",
          ],
          visual: { kicker: "Asset workflow", title: "Generate, inspect, naturalize", items: ["Prompt and iterate", "Check historical and visual coherence", "Refine texture and lighting", "Prepare assets for scene integration"] },
          caption: "Generative tools accelerate asset exploration while curation and post-processing preserve visual authorship.",
        },
        {
          key: "cinema",
          label: "04 · Virtual production",
          title: "The film is staged in a real-time engine with the logic of a physical set.",
          paragraphs: [
            "Unreal Engine 5 becomes the production space. I use Lumen for global illumination and Sequencer for camera, performance, timing, and render control before moving into final editing and sound design.",
            "Working in-engine makes it possible to revise light, blocking, and lens choices together instead of locking each element into a one-way effects pipeline.",
          ],
          visual: { kicker: "UE5 pipeline", title: "A controllable virtual set", items: ["Scene assembly", "Lumen lighting", "Sequencer camera and timing", "Render, edit, and sound"] },
          caption: "Real-time production keeps cinematography, character direction, and environment revision in the same loop.",
        },
        {
          key: "question",
          label: "05 · Why this experiment matters",
          title: "Can independent filmmakers depict historically specific worlds without inheriting studio-scale constraints?",
          paragraphs: [
            "The project tests whether AI-generated visuals and game-engine production can form a credible alternative pipeline for stories that would otherwise require costly locations, period sets, and casting.",
            "I am interested not only in efficiency but in authorship: which decisions remain meaningfully mine, where generated material introduces risk, and how a small team can preserve historical and emotional specificity.",
          ],
          visual: { kicker: "Creative research question", title: "A new production model", items: ["Lower physical-production barriers", "Keep narrative control", "Make iteration reversible", "Document ethical and aesthetic tradeoffs"] },
          caption: "The film is both a creative work and an experiment in the organization of independent production.",
        },
      ],
      outcome: {
        label: "In progress",
        title: "The next milestone is a coherent proof-of-concept sequence.",
        body: "The immediate goal is to complete a sequence that demonstrates character consistency, historical atmosphere, directed performance, and a coherent AI plus UE5 production workflow—not just a collection of attractive frames.",
      },
    },
  },

  nongming: {
    eyebrow: "Education design · UNESCO Global Higher Education finalist",
    title: "Nongming: Smart Farming, Bright Future",
    summary: "A cooperative simulation game that makes smart farming tangible through data, missions, and shared problem-solving.",
    role: "Team leader responsible for the educational concept, prototype direction, and finalist presentation.",
    methods: "Unity WebGL; Photon networking; role-based multiplayer; environmental simulation; mission and feedback design.",
    finding: "The design reframes agriculture as a data-driven future field while giving students a safe space to test decisions and learn from failure.",
    image: "assets/detail/nongming/thumbnail.png",
    links: [{ label: "View presentation ↗", url: "https://www.canva.com/design/DAGo11pBMtY/EPZW78PrvzOjCZI_BeM6Vg/view" }],
    caseStudy: {
      meta: ["Educational game", "UNESCO GHE finalist", "Unity WebGL", "Cooperative simulation"],
      map: [
        { label: "Gap", title: "Agriculture changed; classroom images did not" },
        { label: "Game", title: "Operate a smart farm instead of reading about it" },
        { label: "Loop", title: "Turn sensor evidence into team decisions" },
        { label: "Learning", title: "Make complexity safe to explore" },
        { label: "Value", title: "Connect agriculture with future skills" },
      ],
      role: {
        title: "I led the educational framing and prototype direction.",
        body: "I translated the gap between future agriculture and school instruction into a game concept, shaped the cooperative learning loop, coordinated prototype development, and presented the work through the UNESCO finalist process.",
        tags: ["Team leadership", "Learning design", "Game systems", "Prototype direction", "Presentation"],
      },
      sections: [
        {
          key: "gap",
          label: "01 · The education gap",
          title: "Agriculture remains essential, but students rarely encounter its data-driven reality.",
          paragraphs: [
            "Food security, carbon neutrality, biotechnology, and sustainability all depend on agriculture. Yet school exposure is shrinking and often remains theoretical, so students continue to associate farming with difficult manual labor rather than sensing, automation, and AI.",
            "Nongming began from this disconnect: smart-farm technology was being described as future infrastructure, but learners had few chances to operate it, make decisions, or see consequences.",
          ],
          alt: "Nongming smart-farming education game",
          caption: "The visual identity presents farming as a collaborative technology system rather than an outdated occupation.",
        },
        {
          key: "game",
          label: "02 · The simulation",
          title: "Students manage a smart farm through a real-time, role-based game.",
          paragraphs: [
            "Players control environmental parameters, respond to missions, and compete while coordinating access to information. Sensors, crop conditions, and operational decisions become interactive rather than abstract vocabulary.",
            "The goal is not to reproduce every detail of farm management. It is to create a legible model in which data, diagnosis, collaboration, and consequences can be practiced together.",
          ],
          image: "assets/detail/nongming/gameplay.png",
          alt: "Nongming gameplay interface",
          caption: "Environmental controls and missions turn smart-farm concepts into actions that can succeed or fail.",
        },
        {
          key: "loop",
          label: "03 · The learning loop",
          title: "A mission becomes an anomaly, a discussion, a decision, and a visible outcome.",
          paragraphs: [
            "Each scenario follows a repeatable loop: receive a task, notice an environmental anomaly, inspect sensor logs, discuss evidence, apply a panel control, and observe the result. Some players receive information that others do not, making communication necessary rather than decorative.",
            "Wrong decisions can damage crops inside the simulation. Immediate feedback and repeatable scenarios make failure informative without creating real-world cost or risk.",
          ],
          image: "assets/detail/nongming/pipeline.png",
          alt: "Nongming mission and learning pipeline",
          caption: "The gameplay loop mirrors practical troubleshooting: evidence must travel through a team before it becomes action.",
        },
        {
          key: "learning",
          label: "04 · Why a game",
          title: "Games combine motivation with the repeated, consequential practice that complex systems require.",
          paragraphs: [
            "Goals, feedback, competition, and collaboration can sustain attention, while balanced challenges help learners enter a flow state. More importantly, simulation makes abstract concepts such as IoT sensing, environmental control, and data interpretation visible and manipulable.",
            "This supports active learning: students form a hypothesis, act, inspect the outcome, and revise. Structured onboarding and replay let proficiency grow across scenarios instead of ending after one correct answer.",
          ],
          visual: { kicker: "Learning affordances", title: "Motivation meets experiential practice", items: ["Immediate feedback", "Safe experimentation", "Team problem-solving", "Progressive complexity"] },
          caption: "The game format is used as a learning mechanism, not simply as an engagement layer.",
        },
        {
          key: "value",
          label: "05 · Educational value",
          title: "The larger aim is a new image of agriculture—and the skills to participate in it.",
          paragraphs: [
            "Nongming reframes farming as a system of data, diagnosis, and coordinated action. Students practice data literacy, collaborative troubleshooting, and ownership of decisions while seeing agriculture as a future-ready field.",
            "The project’s value proposition is therefore both practical and cultural: make smart-farm complexity learnable, and make agricultural futures imaginable to students earlier.",
          ],
          image: "assets/detail/nongming/impact.png",
          alt: "Nongming educational impact framework",
          caption: "The intended shift is from passive theory to experience, skill, and a more contemporary view of agriculture.",
        },
      ],
      outcome: {
        label: "Design principle",
        title: "Future-facing education needs environments where systems can be operated, not only explained.",
        body: "Nongming demonstrates how cooperative simulation can simplify a complex domain without stripping away evidence, consequence, or teamwork.",
      },
    },
  },

  "always-on-ai": {
    eyebrow: "Government-funded research · National Research Foundation of Korea · 2026–2029",
    title: "Proactive AI and Human Cognitive Mechanisms in Always-On AI Environments",
    summary: "A government-supported research program on how continuously available AI can intervene creatively without weakening human judgment, attention, or agency.",
    role: "Researcher contributing to proactive creative-AI systems, prompt-generation engineering, experimental design, and human-centered evaluation; related work has led to a patent application.",
    methods: "Proactive interaction design; context-aware prompt generation; profile granularity; experimental evaluation; curiosity and epistemic-agency measures.",
    finding: "The project treats proactivity as a calibrated human–AI relationship: what the system knows, when it intervenes, and how people retain authorship must be designed together.",
    image: "assets/detail/alwayson/thumbnail.png",
    caseStudy: {
      meta: ["2026–2029", "Government-funded R&D", "National Research Foundation of Korea", "Funded by the Ministry of Science and ICT"],
      map: [
        { label: "Context", title: "Move from requested help to continuous availability" },
        { label: "Boundary", title: "Decide when AI should notice or intervene" },
        { label: "Creativity", title: "Use prompts as provocations, not answers" },
        { label: "Cognition", title: "Measure curiosity, attention, and agency" },
        { label: "Direction", title: "Build accountable proactive systems" },
      ],
      role: {
        title: "I connect the system’s proactive behavior to the human cognitive process it is meant to support.",
        body: "My contribution spans creative-AI interaction, profile and context design, prompt-generation engineering, experiment planning, and the interpretation of psychological outcomes. I am especially interested in when a system can open a productive line of thought without deciding that line for the user.",
        tags: ["Proactive AI", "Creative support", "Prompt engineering", "Experimental HCI", "Epistemic agency"],
      },
      sections: [
        {
          key: "context",
          label: "01 · The new interaction condition",
          title: "An always-on AI does not wait at the edge of a prompt box.",
          paragraphs: [
            "Continuously available systems can observe context and offer help before a person explicitly asks. That promise also changes the core HCI question: the system must infer not only what may be useful, but whether this is the right moment to intervene at all.",
            "The project studies this shift as a cognitive and relational design problem, not simply a faster recommendation pipeline. Helpful proactivity depends on attention, privacy, timing, and the user’s ability to ignore, redirect, or transform an AI suggestion.",
          ],
          alt: "Proactive AI research in an always-on interaction setting",
          caption: "The program is funded through the National Research Foundation of Korea by the Ministry of Science and ICT.",
        },
        {
          key: "boundary",
          label: "02 · Calibrating what the system knows",
          title: "More personal context can make a suggestion relevant—and make it harder to feel like one’s own.",
          paragraphs: [
            "We examine profile granularity, sensed context, and intervention timing as linked design choices. A coarse profile may leave room for interpretation; a fine-grained profile can improve alignment but also narrow the conceptual space or feel intrusive.",
            "The design target is therefore not maximal personalization. It is legible, controllable personalization whose benefit is proportionate to the information it requires.",
          ],
          visual: { kicker: "Calibration problem", title: "Know enough to help; leave enough room to think", items: ["Profile granularity", "Context sensitivity", "Intervention timing", "User control"] },
          caption: "Proactivity is evaluated as a balance among relevance, surprise, privacy, and authorship.",
        },
        {
          key: "creativity",
          label: "03 · Creative intervention",
          title: "A useful proactive prompt should disturb a routine without completing the thought.",
          paragraphs: [
            "My work focuses on prompts that connect a person’s environment to possible questions, analogies, or actions. The system proposes a direction, while the person decides whether to keep, transform, or discard it.",
            "This principle has informed AI-glasses research for research ideation and prompt-generation engineering. It also grounds a patent application on AI prompt generation developed with the research team.",
          ],
          visual: { kicker: "Creative loop", title: "Notice → provoke → choose → develop", items: ["Read the immediate context", "Generate several possible openings", "Let the user accept or redirect", "Preserve the trace of human choice"] },
          caption: "The system is designed as a source of productive friction rather than an automatic author.",
        },
        {
          key: "cognition",
          label: "04 · Human outcomes",
          title: "The outcome is not only whether the suggestion was useful, but what happened to the user’s thinking.",
          paragraphs: [
            "Studies within the program examine curiosity, exploration, perceived usefulness, trust, and epistemic agency. These measures help distinguish a prompt that merely looks impressive from one that actually supports a person’s own inquiry.",
            "The research also attends to heterogeneous users: the same degree of proactivity can function as welcome support, interruption, or overreach depending on goals and cognitive state.",
          ],
          visual: { kicker: "Evaluation", title: "Measure the person, not only the output", items: ["Curiosity and exploration", "Epistemic agency", "Trust and perceived control", "Idea development"] },
          caption: "Psychological outcomes make the cost of a proactive design visible alongside its performance.",
        },
        {
          key: "direction",
          label: "05 · Research direction",
          title: "The long-term goal is proactive AI that is useful because its intervention remains negotiable.",
          paragraphs: [
            "For an always-on system, responsibility begins before the prompt appears. Designers must specify what is sensed, why an intervention was triggered, and how the person can decline or revise it.",
            "This program gives me a shared foundation for studying creative support, cognition, and responsible system behavior as one problem rather than separate features.",
          ],
          visual: { kicker: "Design commitment", title: "Proactive, but not presumptive", items: ["Explain what triggered the intervention", "Make personal data boundaries visible", "Offer refusal and revision", "Evaluate long-term cognitive effects"] },
          caption: "A proactive system should increase possibility without quietly taking over the direction of thought.",
        },
      ],
      outcome: {
        label: "Program significance",
        title: "Always-on AI makes the ethics of timing and inference inseparable from interaction quality.",
        body: "The project is supported by the National Research Foundation of Korea and funded by the Ministry of Science and ICT. Its contribution is a human-centered account of proactive AI that joins system engineering with cognitive and agency-centered evaluation.",
      },
    },
  },

  "child-story": {
    eyebrow: "Government-funded research · Seoul RISE · 2026–2027",
    title: "Semantic Storification Framework",
    summary: "A development-aware story pipeline that connects photographed object features to age-adjusted narrative actions and verifiable story evidence.",
    role: "Contributes to ontology design, developmental rules, prompt architecture, prototyping, validation, and caregiver-facing evaluation.",
    methods: "Object semantics; development-aware prompt policy; structured model review; evidence checks; bounded local repair; versioned caregiver feedback.",
    finding: "The framework makes object use and narrative complexity inspectable while treating developmental effects as an evaluation target—not an unverified claim.",
    image: "assets/detail/rise/architecture.png",
    caseStudy: {
      meta: ["Seoul RISE", "Semantic Storification Framework", "iOS + server pipeline", "21 code checks + 5 integration scenarios"],
      map: [
        { label: "Ground", title: "Separate observed traits from inferred functions" },
        { label: "Adapt", title: "Control language and event complexity together" },
        { label: "Generate", title: "Build problems objects can actually help solve" },
        { label: "Verify", title: "Check evidence and repair only what failed" },
        { label: "Improve", title: "Version shared rules through reviewed feedback" },
      ],
      role: {
        title: "I work across the conceptual and technical layers of developmental storytelling.",
        body: "My contribution connects object ontology, age-adaptive language, narrative constraints, prototype behavior, and evaluation logic so that a child-facing story is not only fluent but traceable to the objects and rules that shaped it.",
        tags: ["Ontology", "Prompt architecture", "Developmental policy", "Validation", "Child-centered evaluation"],
      },
      sections: [
        {
          key: "ground",
          label: "01 · Ground the story",
          title: "A photographed object should solve a problem through features it actually has.",
          paragraphs: [
            "The Semantic Object Interpreter separates visible traits—such as shape, color, or texture—from ordinary object functions. Low-confidence identification triggers caregiver confirmation, and the original recognition record is preserved even after correction.",
            "This distinction prevents the system from presenting invented visual traits as observations. Each object keeps a source index so its eventual story action can be traced back to the input.",
          ],
          alt: "Semantic Storification Framework architecture",
          caption: "SOI interprets objects, NPA structures resolvable events, and DLA adjusts language and event complexity.",
        },
        {
          key: "adapt",
          label: "02 · Adapt complexity",
          title: "Developmental adaptation changes both the words and the number of things a child must coordinate.",
          paragraphs: [
            "Initial engineering levels set different limits for participating objects and resolution steps: one object and two steps for easy stories, two and three for standard stories, and three and four for more complex stories. Language guidance moves from short concrete sentences toward causal explanation and sequential cooperation.",
            "These thresholds are implementation settings to be tested, not established developmental effects. A caregiver can override the age-based default, and the policy version is fixed for the entire generation job.",
          ],
          visual: { kicker: "Initial policy", title: "Language and event structure move together", items: ["Easy: direct resolution", "Standard: observation and attempt", "Complex: reasons, constraints, and sequence"] },
          caption: "The framework makes complexity explicit enough to audit and revise.",
        },
        {
          key: "generate",
          label: "03 · Construct the event",
          title: "The problem is chosen after the objects are understood—not imposed before them.",
          paragraphs: [
            "The Narrative Prompt Architect inspects each object’s traits and plausible actions, then constructs a safe problem those actions can help resolve. Multiple actions serving one resolution goal are grouped as one step, while actions producing separate intermediate results remain distinct.",
            "This keeps the child as an observer and chooser rather than letting the model force unrelated objects into a predetermined plot.",
          ],
          visual: { kicker: "Processing flow", title: "Observe → confirm → adapt → generate", items: ["Analyze photographed objects", "Confirm uncertain identity", "Apply age and caregiver policy", "Generate a resolvable story event"] },
          caption: "The pipeline is built around object–action–resolution consistency.",
        },
        {
          key: "verify",
          label: "04 · Verify and repair",
          title: "Every claimed object action must point to a valid page, feature source, and quotation.",
          paragraphs: [
            "A separate review call returns structured evidence for feature linkage, resolution contribution, and developmental fit. Code then checks object IDs, page ranges, verbatim evidence, source labels, participating-object limits, and grouped resolution steps.",
            "Local violations allow patches only on the affected page and its neighbors; unrelated pages remain untouched. Global violations or failed rechecks trigger full regeneration within fixed attempt limits. Results that never pass are not stored as completed stories.",
          ],
          visual: { kicker: "Bounded repair", title: "Inspect first; change only the permitted scope", items: ["Validate evidence records", "Locate the violation", "Patch local pages or regenerate", "Re-run the complete check"] },
          caption: "Validation prioritizes traceability and bounded revision over silent acceptance of fluent output.",
        },
        {
          key: "improve",
          label: "05 · Improve the shared policy",
          title: "Caregiver feedback informs review, but it does not automatically rewrite developmental rules.",
          paragraphs: [
            "Caregivers can submit a rating and optional comment tied to the story and policy version. Feedback is grouped into language, resolution complexity, object use, and other concerns for operator review.",
            "A new common policy requires comparison on the same evaluation set, a recorded expert review, and operator approval. Current validation includes 21 deterministic checks, five mocked integration scenarios, and three synthetic live-API runs across easy, standard, and complex settings. Real-device and child-outcome evaluation remain future work.",
          ],
          visual: { kicker: "Versioned governance", title: "Feedback → comparison → review → approval", items: ["Preserve generation context", "Review recurring concerns", "Compare candidate policy", "Activate a new version explicitly"] },
          caption: "The feedback loop is designed for accountable revision rather than uncontrolled personalization.",
        },
      ],
      outcome: {
        label: "Technical significance",
        title: "Development-aware generation becomes a traceable system rather than a prompt-level promise.",
        body: "The distinctive connection is between object-level evidence, explicit complexity limits, violation-localized repair, and versioned policy improvement. Empirical developmental benefit remains a question for controlled evaluation.",
      },
    },
  },

  standup: {
    eyebrow: "Inter-university academic festival · 2023",
    title: "Stand-Up Inter-University Convergence Academic Festival",
    summary: "A student-led academic festival connecting approximately 100 students from convergence programs at Sungkyunkwan, Sogang, Ewha Womans, and Dongguk University.",
    role: "Co-founder.",
    methods: "Institutional coordination; program design; faculty recruitment; participant operations; evaluation planning.",
    finding: "The project created a shared academic setting where students could exchange unfinished ideas and initiate collaborations across institutional boundaries.",
    image: "assets/detail/standup/thumbnail.jpg",
    links: [{ label: "Watch video ↗", url: "https://www.youtube.com/watch?v=Z4IrUHiMCIE" }],
    caseStudy: {
      meta: ["2023", "Four universities", "Approximately 100 students", "Student-led organization"],
      map: [
        { label: "Need", title: "Give convergence students a shared academic room" },
        { label: "Partners", title: "Coordinate four universities" },
        { label: "Program", title: "Build exchange around student work" },
        { label: "Operations", title: "Connect faculty, review, and logistics" },
        { label: "Outcome", title: "Make future collaboration possible" },
      ],
      role: {
        title: "Co-founder.",
        body: "I helped recruit and coordinate the convergence programs of Sungkyunkwan University, Sogang University, Ewha Womans University, and Dongguk University. My work joined university partnerships, program planning, evaluation and advisory processes, faculty recruitment, and participant coordination.",
        tags: ["Partnerships", "Program design", "Academic community", "Operations", "Evaluation"],
      },
      sections: [
        { key: "need", label: "01 · The need", title: "Interdisciplinary students often shared a label without sharing a community.", paragraphs: ["Stand-Up was created to give students from related convergence programs a place to present, question, and compare work across universities."], quote: "The project began as student-led academic community building." },
        { key: "partners", label: "02 · Partnerships", title: "Four universities needed a common structure without flattening their differences.", paragraphs: ["We brought together convergence and interdisciplinary programs from Sungkyunkwan University, Sogang University, Ewha Womans University, and Dongguk University.", "I worked across institutional communication, faculty and advisor recruitment, participation criteria, and the practical expectations each school brought to the event."], image: "assets/detail/standup/event-1.jpg", alt: "Students from four universities at the Stand-Up academic festival", caption: "Approximately 100 students gathered from four university communities." },
        { key: "program", label: "03 · Program", title: "The schedule was designed around exchange, not one-way display.", paragraphs: ["Presentation, feedback, and informal discussion formats gave students multiple ways to enter the academic conversation."], visual: { kicker: "Program logic", title: "Show work, receive feedback, find collaborators", items: ["Student presentations", "Cross-university review", "Faculty perspective", "Open networking"] }, caption: "Each format served a different layer of academic exchange." },
        { key: "operations", label: "04 · Operations", title: "Community-building depended on invisible coordination.", paragraphs: ["Partnership communication, evaluation criteria, advisory processes, faculty schedules, and participant logistics had to function as one system."], visual: { kicker: "Coordination", title: "Four institutions, one participant experience", items: ["Partner alignment", "Review process", "Faculty recruitment", "On-site operation"] }, caption: "The work taught me to treat organizational design as part of the intellectual experience." },
        { key: "outcome", label: "05 · Outcome", title: "The festival made interdisciplinary identity concrete through people and work.", paragraphs: ["The result was not only a one-day event but a visible network of peers, faculty, and possible collaborators across universities.", "The experience also showed me that academic exchange has to be deliberately designed: who is invited, how unfinished work can be discussed safely, and how feedback becomes a next connection."], image: "assets/detail/standup/event-2.jpg", alt: "Organizers and faculty discussing student work at Stand-Up", caption: "A shared setting can turn parallel programs into an academic community." },
      ],
      outcome: { label: "What I learned", title: "Research culture can itself be designed.", body: "Stand-Up showed me that collaboration depends on formats, incentives, and relationships—not simply gathering people in the same room." },
    },
  },

  "missionary-theater": {
    eyebrow: "Stage productions · 2022–2023",
    title: "Missionary Theater Productions",
    summary: "Two creative stage productions reimagining biblical narratives through contemporary theatrical language.",
    role: "Writer, director, and production lead across concept, scripting, rehearsal, and performance.",
    methods: "Biblical source interpretation; dramaturgy; scriptwriting; directing; cast coordination; live production.",
    finding: "The productions taught me to move between evidence, narrative interpretation, collective rehearsal, and the constraints of live delivery.",
    image: "assets/detail/missionary-theater/scene-1.jpg",
    caseStudy: {
      meta: ["2022–2023", "Two productions", "Original scripts", "Creative direction"],
      map: [
        { label: "Source", title: "Connect biblical narratives to contemporary questions" },
        { label: "Write", title: "Translate source material into dramatic structure" },
        { label: "Direct", title: "Build meaning collectively in rehearsal" },
        { label: "Stage", title: "Coordinate a live production system" },
        { label: "Reflect", title: "Keep interpretation accountable" },
      ],
      role: { title: "I independently led both productions from concept to performance.", body: "My role covered source interpretation, concept development, writing, directing, rehearsal design, cast coordination, and live production.", tags: ["Concept", "Writing", "Directing", "Rehearsal", "Production"] },
      sections: [
        { key: "research", label: "01 · Source and concept", title: "Each production began by finding a contemporary question inside a biblical narrative.", paragraphs: ["I interpreted biblical source material through present-day emotions, conflicts, and relationships, then shaped a theatrical concept that could speak to a contemporary audience."] },
        { key: "write", label: "02 · Writing", title: "The scripts brought biblical narratives into a contemporary theatrical voice.", paragraphs: ["I developed the dramatic structure, dialogue, and transitions while balancing the source material with original interpretation and modern performance language."], image: "assets/detail/missionary-theater/scene-2.jpg", alt: "Actors performing a missionary theater production", caption: "Writing connected biblical narratives with the rhythm and language of contemporary theater." },
        { key: "direct", label: "03 · Directing", title: "The script became a shared object that actors could test and reshape.", paragraphs: ["Rehearsal exposed what the page could not: pacing, emotional credibility, spatial relationships, and where explanation needed to become action."], image: "assets/detail/missionary-theater/scene-3.jpg", alt: "Missionary theater ensemble on stage", caption: "Directing turned interpretation into collective physical decisions." },
        { key: "stage", label: "04 · Production", title: "The final experience depended on many systems arriving at the same moment.", paragraphs: ["Casting, rehearsal, staging, technical cues, and live coordination had to remain coherent under the irreversible timing of performance."], visual: { kicker: "Production system", title: "Text → rehearsal → stage", items: ["Cast coordination", "Blocking and pacing", "Technical cues", "Live operation"] }, caption: "Production leadership joined creative direction with operational responsibility." },
        { key: "reflect", label: "05 · Reflection", title: "Creative authority also means responsibility for how sacred narratives are reframed.", paragraphs: ["The productions strengthened my interest in technologies that expand creative possibility without obscuring authorship, interpretation, or consequence."] },
      ],
      outcome: { label: "Creative continuity", title: "Theater became the foundation for my later virtual-production work.", body: "Writing, directing, and coordinating live performance gave me the narrative and production vocabulary I now bring to MetaHuman and Unreal Engine filmmaking." },
    },
  },
};
