const benevolenceMap = {
  question: "If an AI gives up its own reward to help us, what makes us reciprocate instead of exploit it?",
  answer: "Cooperation rose when the AI felt socially present, but fell when the personal reward at stake became larger.",
  meta: ["N = 52", "2 × 2 between-subjects + repeated reward round", "Modified Reciprocity Game", "R / ANOVA"],
  role: {
    title: "I carried this study from question to CHI stage.",
    body: "As sole author and principal investigator, I framed the problem, designed and implemented the experiment, collected and analyzed the data, wrote the paper, and presented it at the ACM CHI Student Research Competition.",
    tags: ["Research framing", "Experiment design", "Labvanced study", "R analysis", "Sole-author writing"],
  },
  nodes: [
    {
      key: "intro", label: "01 · Intro", title: "Benevolence can invite cooperation—or invite exploitation.",
      paragraphs: [
        "AI systems increasingly act in ways that look helpful, patient, or self-sacrificing. Yet a cooperative machine does not automatically receive cooperation in return. I wanted to understand the point at which people stop treating an AI as a resource and start responding to it as a social partner.",
        "The study turns that tension into a simple exchange: an AI repeatedly cooperates, while the human decides whether to reciprocate or keep the larger payoff.",
      ],
      figures: [{ src: "assets/papers/benevolence-design.png", alt: "Four experimental conditions and the modified reciprocity game", caption: "The experiment crossed social presence with reward clarity, then increased the reward in a second round." }],
    },
    {
      key: "lit", label: "02 · Short lit review", title: "Two forces seemed likely to compete: social obligation and self-interest.",
      paragraphs: [
        "Reciprocity research suggests that perceived intentionality and social presence can make kindness feel morally binding. Work on algorithm exploitation, however, shows that people may take advantage of systems that cannot retaliate or suffer in an obvious way.",
        "I therefore separated relational cues from economic incentives: does a more socially present AI encourage reciprocity, and can a larger reward override that effect?",
      ],
    },
    {
      key: "method", label: "03 · Method", title: "A cooperative AI, four social conditions, and a changing stake.",
      paragraphs: [
        "Fifty-two participants played a Modified Reciprocity Game in one of four conditions crossing social presence (human–AI framing vs. AI framing) and reward-system clarity (clear vs. ambiguous). A Wizard-of-Oz opponent cooperated in every round so that the human response—not AI strategy—remained the focus.",
        "Reward size doubled in the second round. The study ran in Labvanced with Zoom screen monitoring, and I analyzed reciprocal cooperation using ANOVA and regression in R.",
      ],
      stats: [{ value: "52", label: "participants" }, { value: "4", label: "experimental conditions" }, { value: "2×", label: "reward increase" }],
      figures: [{ src: "assets/papers/benevolence-design.png", alt: "Experimental conditions and reward manipulation", caption: "A controlled game made social presence and self-interest independently testable." }],
    },
    {
      key: "results", label: "04 · Results", title: "Feeling a social partner helped; seeing a bigger payoff did the opposite.",
      paragraphs: [
        "Higher social presence increased reciprocal cooperation (F(1,102) = 4.073, p = .046). When the reward became larger, cooperation decreased (F(1,102) = 4.792, p = .031). Reward clarity did not produce a reliable effect, and the interaction was not significant.",
        "The surprising part was that people could report guilt and still choose the more exploitative option when the incentive grew. A relational cue mattered, but it did not erase self-interest.",
      ],
      stats: [{ value: "+", label: "social presence → cooperation" }, { value: "−", label: "larger reward → cooperation" }, { value: "n.s.", label: "reward clarity" }],
      figures: [{ src: "assets/papers/benevolence-results.png", alt: "Cooperation results by social presence and reward size", caption: "The two clearest effects moved in opposite directions." }],
    },
    {
      key: "discussion", label: "05 · Discussion", title: "Responsible AI needs to design the relationship, not only the reward rule.",
      paragraphs: [
        "The results suggest that cooperative behavior toward AI is jointly shaped by relational design and incentive structure. Social presence can discourage exploitation, but stronger material incentives may still pull users toward self-interest.",
        "This matters beyond games: autonomous vehicles, financial agents, and public-service AI all make decisions that distribute benefits and costs. My next question is how systems can invite responsibility without manipulating users through artificial intimacy.",
      ],
    },
  ],
};

const goodbyeMap = {
  question: "If an AI companion must disappear, can two minutes of warning make the ending meaningfully less painful?",
  answer: "Yes. A brief, intentional transition reduced loss without making the service feel worse—and the larger follow-up replicated the effect.",
  meta: ["Original N = 26", "Immersive AI companion", "Xreal Air 2 Pro", "ANCOVA + robustness checks"],
  role: {
    title: "I treated the ending as part of the interaction design.",
    body: "As co-first author, I helped design and run the immersive study, analyze the emotional-loss outcomes, interpret attachment effects, and translate the evidence into responsible offboarding guidance. I continued the line into the larger Goodbyes Matter full-paper study.",
    tags: ["Co-first author", "Immersive experiment", "Statistical analysis", "Ethical offboarding", "Follow-up study"],
  },
  nodes: [
    { key: "intro", label: "01 · Intro", title: "Most AI research studies how relationships begin. I wanted to study how they end.", paragraphs: ["People can disclose personal experiences and build routines with conversational AI, yet a shutdown, model change, or lost account can end that relationship without warning. I became interested in whether a small piece of interaction design could protect users at that vulnerable moment.", "The key idea was intentionally modest: not preventing termination, but giving the user enough time to understand it and close the interaction."], figures: [{ src: "assets/papers/goodbyes-flow.png", alt: "Immersive AI offboarding study flow", caption: "The companion interaction stayed the same until the final two-minute termination period." }] },
    { key: "lit", label: "02 · Short lit review", title: "Attachment makes separation meaningful, but offboarding is rarely designed as a relationship event.", paragraphs: ["Research on parasocial bonds, digital grief, and relational agents shows that users can experience genuine loss around mediated relationships. Service termination research usually focuses on usability, data, or migration—not on emotional closure.", "We asked whether forewarning would reduce loss and whether the effect would be especially strong for people who had formed a stronger bond." ] },
    { key: "method", label: "03 · Method", title: "The same fifteen-minute relationship, followed by two different endings.", paragraphs: ["Twenty-six participants interacted with an immersive AI companion through Xreal Air 2 Pro glasses. After a fifteen-minute rapport-building conversation, one group received an on-screen warning and a final two minutes; the other experienced sudden termination.", "We compared emotional-loss responses with ANCOVA while controlling for emotional bond, then checked the result with bootstrap and rank-based analyses."], stats: [{ value: "15 min", label: "rapport building" }, { value: "2 min", label: "forewarned closure" }, { value: "2 groups", label: "warning vs. sudden" }], figures: [{ src: "assets/papers/goodbye-results.png", alt: "Original study loss results", caption: "Forewarning lowered overall loss and several component emotions." }] },
    { key: "results", label: "04 · Results", title: "A short warning changed the emotional landing.", paragraphs: ["Forewarning reduced overall loss (B = −0.749, p = .011, partial η² = .252). Sadness showed the largest item-level effect (d = −0.83), and the pattern did not come with worse service evaluations.", "The original sample suggested stronger protection among highly bonded users, but that interaction needed a larger test."], stats: [{ value: "−0.749", label: "adjusted loss difference" }, { value: ".252", label: "partial η²" }, { value: "−0.83", label: "sadness effect size" }], figures: [{ src: "assets/papers/goodbye-bond.png", alt: "Emotional bond and forewarning interaction", caption: "The pilot suggested attachment might shape who benefits most from warning." }] },
    { key: "discussion", label: "05 · Discussion", title: "A responsible relationship includes a responsible exit.", paragraphs: ["Termination should not be treated as a technical afterthought. Even lightweight notice can preserve continuity, explain what is happening, and give users a chance to say goodbye.", "The design challenge is to provide closure without pretending the system has human feelings. That means honest language, clear timing, memory and data options, and support when the ending is consequential." ] },
    { key: "followup", label: "06 · Follow-up", badge: "In submission", title: "Goodbyes Matter replicated the effect and widened the design framework.", paragraphs: ["In the full-paper follow-up (N = 56), forewarning again reduced loss (B = −0.711, p < .001, d = −0.87, partial η² = .225). The result survived HC3, bootstrap, permutation, rank, and influence checks; immersion was identical across conditions.", "The bond interaction was inconclusive (p = .080), arguing against reserving notice only for visibly attached users. Dialogue analysis also showed that deep disclosure often happened before the final two minutes, so systems may need to prepare for termination throughout the relationship.", "The resulting Five-Function Framework covers Notice, Transition, Intentional Closure, Data and Memory Continuity, and Post-termination Support and Recourse."], stats: [{ value: "56", label: "follow-up participants" }, { value: "−0.87", label: "loss effect size" }, { value: "5", label: "offboarding functions" }], figures: [{ src: "assets/papers/goodbyes-results.png", alt: "Replication and robustness results", caption: "The larger study replicated the loss reduction across multiple estimators." }, { src: "assets/papers/goodbyes-framework.png", alt: "Five-function relational offboarding framework", caption: "A practical framework connects evidence to product and policy decisions." }] },
  ],
};

const proactiveMap = {
  question: "Should proactive AI know more about you to inspire better ideas—or does knowing less give it room to surprise you?",
  answer: "A detailed profile increased curiosity in the first study, but the follow-up revealed a deeper gap: diverse AI output does not automatically become diverse human ideas.",
  meta: ["Xreal Air 2 Pro", "Environment-aware micro-prompts", "Profile granularity experiment", "Mixed quantitative + qualitative analysis"],
  role: {
    title: "I worked across the system, study, and interpretation.",
    body: "As co-first author, I contributed to the proactive-AI concept, smart-glasses study design and operation, quantitative and qualitative analysis, and publication development. I then helped extend the work from psychological response to the relationship between system-level diversity and human ideation.",
    tags: ["Co-first author", "AR / proactive AI", "Experimental design", "R analysis", "Qualitative coding"],
  },
  nodes: [
    { key: "intro", label: "01 · Intro", title: "Proactive AI can interrupt before a user asks—so what should it know first?", paragraphs: ["Always-on AI can see the environment and offer ideas at the moment they become relevant. The same capability creates a design tension: rich profiles may produce personally resonant prompts, while sparse profiles may allow wider and more surprising associations.", "I was interested in profile granularity not only as a privacy choice, but as a cognitive design parameter."], figures: [{ src: "assets/papers/sss-method.png", alt: "See Sense Spark experimental system and first-person view", caption: "Micro-prompts appeared through smart glasses while researchers explored a physical space." }] },
    { key: "lit", label: "02 · Short lit review", title: "Personalization can increase relevance while quietly narrowing exploration.", paragraphs: ["Recommender and creativity-support research often treats personalization as a route to usefulness. Creativity research, however, distinguishes interest-driven curiosity from the tension of an unresolved knowledge gap and warns that overfitting can reduce serendipity.", "We therefore compared a coarse profile containing basic academic information with a fine-grained profile containing current topics, projects, and interests." ] },
    { key: "method", label: "03 · Method", title: "The environment supplied the cue; profile depth shaped the prompt.", paragraphs: ["The system used visual input from Xreal Air 2 Pro glasses and a Gemini-powered pipeline to generate short research-ideation prompts. Candidate prompts were gated by a scoring rule combining novelty, major alignment, delight, utility, and exploration potential.", "Twenty researchers completed the original study; seventeen remained after exclusions (coarse n = 8, fine n = 9). They explored for fifteen minutes, then completed psychological measures and a scripted ElevenLabs interview."], stats: [{ value: "15 min", label: "situated exploration" }, { value: "5", label: "prompt-scoring dimensions" }, { value: "2", label: "profile conditions" }], figures: [{ src: "assets/papers/proactive-system.png", alt: "Profile granularity and proactive ideation pipeline", caption: "The follow-up system makes the profile-to-prompt transformation explicit." }] },
    { key: "results", label: "04 · Results", title: "More personal context increased interest-driven curiosity—not every outcome.", paragraphs: ["Fine-grained profiles produced significantly higher I-type curiosity (p = .016, d = 1.30) and a marginal increase in epistemic agency (p = .066, d = .98). Coarse-profile participants more often described prompts in pragmatic, utility-oriented terms.", "The finding challenged our initial intuition that less profile information would automatically broaden exploration."], stats: [{ value: "1.30", label: "I-type curiosity d" }, { value: ".98", label: "epistemic agency d" }, { value: "4", label: "emergent user clusters" }], figures: [{ src: "assets/papers/sss-results.png", alt: "See Sense Spark factor and cluster results", caption: "Curiosity and agency shifted more clearly than broad satisfaction or trust." }] },
    { key: "discussion", label: "05 · Discussion", title: "Profile depth is not simply a privacy slider; it changes the mode of thinking.", paragraphs: ["Fine profiles can help users feel that an idea belongs to their own line of inquiry. Coarse profiles may support utilitarian reframing, but surprise alone does not guarantee productive appropriation.", "The design opportunity is adaptive granularity: change how much the system knows—and how tightly it uses that knowledge—across different phases of creative work." ] },
    { key: "followup", label: "06 · Follow-up", badge: "In submission", title: "How Much Should Proactive AI Know? exposed a system–participant divergence gap.", paragraphs: ["The follow-up studied 26 researchers and analyzed 24 complete interaction logs. Coarse-profile AI output was objectively broader: peripheral-object content appeared in 42% of coarse prompts versus 4% of fine prompts, and new interpretive frames in 86% versus 26%.", "Yet participant idea breadth and self-reports did not differ reliably. One exploratory tail pattern went the other way: distant combinations appeared for 9 of 14 fine-profile participants versus 2 of 12 coarse-profile participants (OR = 9.0, p = .021).", "The central lesson is that system-level diversity and human-level ideation must be measured separately. A model can diverge without helping a person appropriate that divergence."], stats: [{ value: "42% vs 4%", label: "peripheral-object content" }, { value: "86% vs 26%", label: "new interpretive frames" }, { value: "9.0", label: "exploratory tail OR" }], figures: [{ src: "assets/papers/proactive-system-results.png", alt: "System-level content differences by profile condition", caption: "Coarse profiles visibly diversified the AI's output." }, { src: "assets/papers/proactive-human-results.png", alt: "Participant-level ideation outcomes", caption: "That system-level diversity did not transfer cleanly into participant-level breadth." }] },
  ],
};

window.researchDetails = {
  benevolence: { eyebrow: "Research trajectory · HCI Korea → CHI SRC → TIS", title: "When Do Humans Reciprocate AI?", summary: "An undergraduate research question that grew into a multi-study program on AI benevolence, human consequences, incentives, and guilt.", role: benevolenceMap.role.body, methods: "Modified Reciprocity Game; N = 52 → N = 79; staged behavioral analysis; R.", finding: benevolenceMap.answer, paper: "https://dl.acm.org/doi/pdf/10.1145/3706599.3719279", page: "research/benevolence.html", researchMap: benevolenceMap },
  exploitation: { eyebrow: "Proceedings · HCI Korea 2025", title: "When the AI Exploitation Disappears", summary: "The earlier Korean-language study in the research line that became The Benevolence Paradox.", role: "First author. Led framing, experiment design, quantitative analysis, and writing.", methods: "Modified Reciprocity Game; factorial experiment; R.", finding: benevolenceMap.answer, paper: "https://www.dbpia.co.kr/journal/articleDetail?nodeId=NODE12131515", page: "research/benevolence.html", researchMap: { ...benevolenceMap, meta: ["Earlier study version", "HCI Korea 2025", "Modified Reciprocity Game", "R / ANOVA"], role: { ...benevolenceMap.role, title: "I built the first version of this research line.", body: "As first author, I developed the initial research question, designed and ran the experiment, analyzed the cooperation patterns, and wrote the Korean proceedings paper. The work later grew into the sole-authored CHI Student Research Competition paper." } } },
  goodbye: { eyebrow: "Publication · CHI Extended Abstracts 2026", title: "No Time to Say Goodbye", summary: "An immersive experiment on whether a small amount of warning can soften the loss of an AI companion.", role: goodbyeMap.role.body, methods: "Immersive between-subjects study; Xreal Air 2 Pro; ANCOVA and robustness checks.", finding: goodbyeMap.answer, image: "assets/publication-goodbye-web.jpg", paper: "https://dl.acm.org/doi/pdf/10.1145/3772363.3798687", page: "research/no-time-to-say-goodbye.html", researchMap: goodbyeMap },
  sss: { eyebrow: "Publication · SIGGRAPH Asia 2025 Posters", title: "See, Sense, Spark", summary: "A proactive smart-glasses system exploring how profile granularity shapes curiosity and creative ideation.", role: proactiveMap.role.body, methods: "Xreal Air 2 Pro; Gemini; profile manipulation; mixed-method analysis.", finding: proactiveMap.answer, image: "assets/publication-sss-poster-web.png", paper: "https://dl.acm.org/doi/full/10.1145/3757374.3771458", page: "research/see-sense-spark.html", links: [{ label: "Demo video ↗", url: "https://youtu.be/kbhWUENajDM?si=b6m7_Tjsb87YCoGQ" }], researchMap: proactiveMap },
  homophily: {
    eyebrow: "Manuscript under review", title: "Homophily in Voice-Based AI", summary: "A voice-agent study of whether social matching creates genuine support or merely demographic resemblance.",
    role: "First author. Led framing, study design, analysis, and manuscript development.", methods: "N = 140; 2 × 2 age × regional persona experiment; GPT-4o; ElevenLabs; R.", finding: "Matching was selective, not universal: age congruence helped older adults, while regional congruence mainly increased perceived similarity in Texas.", page: "research/homophily-voice-ai.html", links: [{ label: "Demo video ↗", url: "https://youtu.be/fIHGNQhxkyE?si=cRXqr7V3E5IYFjcp" }],
    researchMap: { question: "Can an AI voice feel more supportive when it sounds socially close to you—or does demographic matching oversimplify identity?", answer: "There was no universal matching advantage. Age and region mattered for different people, through different relational pathways.", meta: ["N = 140", "2 × 2 voice-persona experiment", "GPT-4o + ElevenLabs", "ANCOVA / R"], role: { title: "I led the study from identity theory to statistical model.", body: "As first author, I framed the homophily question, designed the age and regional persona manipulation, led analysis and interpretation, and developed the manuscript.", tags: ["First author", "Voice-agent design", "Online experiment", "ANCOVA", "Manuscript lead"] }, nodes: [
      { key: "intro", label: "01 · Intro", title: "A familiar voice can feel close—but identity is more than a demographic match.", paragraphs: ["Voice agents increasingly provide emotional support, and designers often personalize them through accents, age cues, or speaking style. I wanted to know whether this kind of matching actually improves support—or whether its value depends on which identity is meaningful in context.", "Rather than assuming homophily always works, the study treats age and region as distinct social signals."], figures: [{ src: "assets/papers/homophily-model.png", alt: "Conceptual model for voice-agent identity congruence", caption: "Identity congruence was expected to shape similarity, social presence, support, and user experience." }] },
      { key: "lit", label: "02 · Short lit review", title: "Similarity can reduce social distance, but category salience is contextual.", paragraphs: ["Homophily and communication accommodation theories predict that people respond more favorably to socially similar partners. CASA research suggests these expectations can extend to artificial agents.", "But age and regional identity do not carry the same weight for every user. We therefore asked not only whether congruence helps, but for whom and through which perceptions." ] },
      { key: "method", label: "03 · Method", title: "Four versions of the same supportive agent isolated two identity cues.", paragraphs: ["One hundred forty younger and older adults from Texas and New York spoke with one of four male-voiced agents crossing younger/older age persona and Texas/New York regional persona. Each conversation lasted about 6.5 minutes and followed the same emotional-support structure.", "GPT-4o generated the dialogue and ElevenLabs produced the voices. Recruitment, manipulation checks, relational perceptions, support outcomes, and UX measures were analyzed in R."], stats: [{ value: "140", label: "participants" }, { value: "4", label: "voice personas" }, { value: "6.5 min", label: "support conversation" }], figures: [{ src: "assets/papers/homophily-method.png", alt: "Recruitment groups, agent personas, and manipulation checks", caption: "Age and region were crossed while the agent's task and interaction structure stayed constant." }] },
      { key: "results", label: "04 · Results", title: "Age matching improved experience for older adults; regional matching changed similarity more than support.", paragraphs: ["Among older adults, age-congruent agents improved usefulness, attitude, and satisfaction (Fs = 7.03–14.16, ps ≤ .011). Their satisfaction was highest when both age and region matched, a provisional two-cue pattern (F = 6.02, p = .018).", "For Texas participants, regional congruence increased perceived similarity (F = 8.39, p = .005), but broader UX effects were weaker. Matching therefore worked selectively rather than as a universal personalization rule."], figures: [{ src: "assets/papers/homophily-age-result.png", alt: "Older adult outcomes by age congruence", caption: "Age congruence mattered most clearly for older adults' experience." }, { src: "assets/papers/homophily-region-result.png", alt: "Regional congruence effects for Texas and New York participants", caption: "Regional matching shifted perceived similarity in a community-salient context." }] },
      { key: "discussion", label: "05 · Discussion", title: "Voice personalization should offer socially responsive choices, not assign identity by demographic profile.", paragraphs: ["The study argues against a simple matching heuristic. A voice can resonate through age, place, both, or neither, and the meaningful cue depends on the user and context.", "For supportive AI, the safer design direction is transparent choice and adaptation rather than automatic demographic stereotyping. I want to test how users actively negotiate voice identity over longer relationships." ] },
    ] }
  },
  chatbots: {
    eyebrow: "Manuscript under review · Computers in Human Behavior", title: "Chatbots that Comfort: Informational Support is Key for Worry Reduction", summary: "A controlled N = 123 chatbot experiment asking what actually reduces worry: empathic style, useful guidance, or the feeling of social presence.",
    role: "Second author. Contributed to research framing, statistical analysis, and manuscript development.", methods: "N = 123; GPT-4o; between-subjects experiment; parallel mediation SEM and moderation in R.", finding: "Informational clarity was the more reliable mechanism of worry reduction; social presence amplified support perceptions across both styles.", page: "research/chatbots-that-comfort.html",
    researchMap: { question: "When an AI comforts us, is relief coming from simulated empathy—or from finally getting clear, usable guidance?", answer: "Both perceived support types mattered, but informational support was the reliable pathway created by the experimental manipulation.", meta: ["N = 123", "Emotional vs. informational chatbot", "GPT-4o / Flask", "SEM + moderation"], role: { title: "I helped turn a broad comfort question into a testable mechanism model.", body: "As second author, I contributed to the conceptual framing, statistical analysis, interpretation of the mediation and moderation results, and manuscript development.", tags: ["Theory development", "SEM in lavaan", "Moderation analysis", "Interpretation", "Writing"] }, nodes: [
      { key: "intro", label: "01 · Intro", title: "A comforting tone is visible. The mechanism behind comfort is less obvious.", paragraphs: ["Chatbots often combine warm language with practical advice, which makes it difficult to know what actually helps. I was drawn to the gap between an interaction that sounds empathic and one that measurably reduces worry.", "We separated emotional and informational support while keeping the interface, timing, and language model constant."], figures: [{ src: "assets/papers/chatbot-dialogue.png", alt: "Emotional and informational chatbot dialogue examples", caption: "The conditions differed in support strategy, not in platform or interaction length." }] },
      { key: "lit", label: "02 · Short lit review", title: "Support can work through feeling understood, knowing what to do, or both.", paragraphs: ["Social-support theory distinguishes emotional support from informational support. Human–AI research adds social presence and beliefs about AI agency or emotional capacity as possible amplifiers.", "We tested whether chatbot type reduced worry through perceived emotional or informational support, and whether users' beliefs about AI changed those perceptions." ] },
      { key: "method", label: "03 · Method", title: "One five-minute conversation, two deliberately different support strategies.", paragraphs: ["One hundred twenty-three U.S. participants discussed a worry with either an emotional-support chatbot or an informational-support chatbot. The Flask interface, GPT-4o backend, and conversation duration were held constant.", "Parallel mediation was estimated in lavaan with 5,000 bootstrap samples. OLS models tested social presence and beliefs about AI agency and emotional capacity."], stats: [{ value: "123", label: "participants" }, { value: "5 min", label: "chat interaction" }, { value: "5,000", label: "bootstrap samples" }], figures: [{ src: "assets/papers/chatbot-interface.png", alt: "Chatbot onboarding and conversation interface", caption: "A controlled interface kept the manipulation focused on support strategy." }, { src: "assets/papers/chatbot-mediation.png", alt: "Parallel mediation model", caption: "The model separated perceived emotional and informational support." }] },
      { key: "results", label: "04 · Results", title: "Clear guidance carried the experimental effect; warmth still mattered when users perceived it.", paragraphs: ["The informational chatbot increased perceived informational support, and the indirect pathway to worry reduction through informational support was significant (0.476, 95% CI [0.168, 0.861]). The emotional indirect pathway was not significant.", "Perceived emotional and informational support both directly predicted lower worry, and together explained the most variance (β = .75, R² = .54). Social presence had strong additive effects on both kinds of support but did not mediate chatbot type."], stats: [{ value: ".476", label: "informational indirect effect" }, { value: ".54", label: "combined-support R²" }, { value: "n.s.", label: "emotional indirect path" }], figures: [{ src: "assets/papers/chatbot-support-results.png", alt: "Effects of support types on worry reduction", caption: "What users actually perceived mattered more than merely labeling a chatbot empathic." }] },
      { key: "discussion", label: "05 · Discussion", title: "Design clarity first, then add presence without overpromising empathy.", paragraphs: ["The result does not mean emotional support is irrelevant. It means an emotional script alone did not reliably create the mechanism we expected, while concrete guidance did.", "For mental-health-adjacent systems, a responsible default is actionable informational support, light-touch validation, and transparent boundaries around what the AI can understand or feel." ] },
    ] }
  },
  phodong: {
    eyebrow: "Publication · HCI Korea 2026", title: "Phodong", summary: "A vision-and-LLM platform that turns everyday objects into shared story material for parents and children.", role: "Research · Business (app development) · Educational content and community service.", methods: "Object recognition; multimodal LLM; structured character data; web storybook and audiobook output.", finding: "The prototype positions AI as a partial narrative scaffold—not a finished-story generator—so the family keeps creative agency.", paper: "https://www.dbpia.co.kr/journal/voisDetail?voisId=VOIS00810329", page: "research/phodong.html",
    researchMap: { question: "Can AI help a family build a story together without taking the story away from them?", answer: "Phodong uses AI to supply characters and openings, while parents and children remain the people who connect, reinterpret, and complete the narrative.", meta: ["Object recognition", "Multimodal LLM", "Parent–child co-creation", "HCI Korea 2026"], role: { title: "Research, business, and education in one continuing project.", body: "Phodong connects HCI research with ongoing app development and beta testing, commercialization, public exhibitions, and educational content used in community workshops and service activities.", tags: ["Research", "App development", "Business", "Educational content", "Community service"] }, nodes: [
      { key: "intro", label: "01 · Intro", title: "Children have more stories around them than a screen can show.", paragraphs: ["Many children's digital experiences still center on passive consumption, while parents are either excluded or asked to carry the full creative burden. We started from the everyday objects already present in family life.", "The question was not how to generate a better story automatically, but how to give a parent and child enough material to invent one together." ] },
      { key: "lit", label: "02 · Short lit review", title: "Joint media engagement and material anchoring point toward shared authorship.", paragraphs: ["Joint Media Engagement emphasizes meaning made through conversation around media. Distributed cognition and material anchoring show how physical objects can hold and move ideas across people.", "Vygotskian scaffolding suggested a design principle: the system should offer partial support that expands what the family can do without finishing the task for them." ] },
      { key: "method", label: "03 · System", title: "An object becomes a character, then a story card, then part of a shared narrative.", paragraphs: ["A parent sets the child's name, age, preferred genre, and learning goal. Object recognition captures visual features, and a multimodal LLM returns structured JSON for a persona and opening dialogue.", "Each object becomes a story card. Families arrange and connect cards, then revisit the sequence as a web storybook or audiobook. Generation is asynchronous so the interaction can keep moving."], figures: [{ src: "assets/papers/phodong-system.png", alt: "Phodong camera, story card, and storybook screens", caption: "The pipeline moves from a photographed object to reusable narrative material." }] },
      { key: "results", label: "04 · Design contribution", title: "The prototype demonstrates a different division of creative labor.", paragraphs: ["This paper presents a system and design rationale, not an outcome study, so we do not claim measured effects on children's creativity. Its contribution is the interaction structure: AI generates a partial narrative scaffold while the family supplies interpretation, sequencing, and play.", "That distinction matters. A complete story may look impressive while leaving little room for a child or parent to author anything."], figures: [{ src: "assets/papers/phodong-flow.png", alt: "Phodong process and example generated outputs", caption: "The system deliberately leaves decisions between cards to the family." }] },
      { key: "discussion", label: "05 · Discussion", title: "Child-facing AI should be evaluated by how it distributes agency.", paragraphs: ["For co-creative systems, output quality is only one outcome. We also need to ask who introduces ideas, who changes them, and whether the parent and child can build on one another.", "The next research step is a child-centered field evaluation across developmental stages and family contexts. The separate Projects page will later document that wider product and field journey." ] },
    ] }
  },
  "on-the-desk": {
    eyebrow: "Master's thesis · Full paper in submission to ACM/IEEE HRI 2027", title: "When AI Has a Body", summary: "Thesis research on how physical embodiment changes implicit mind perception and when perceived AI agency becomes morally meaningful.", role: "Sole author and principal investigator. Developed the theory, matched systems, study, analysis, and manuscript.", methods: "N = 69; physical robot vs. matched virtual avatar; SC-IAT; regression and moderation in R.", finding: "Physical embodiment increased implicit Experience and made changes in implicit Agency predict Moral Agency—without changing explicit ratings.", image: "assets/publication-embodiment-web.png", page: "research/on-the-desk.html",
    researchMap: { question: "Does putting the same AI body on the desk—not the screen—change when we treat its actions as morally meaningful?", answer: "Physical co-presence did not simply add moral status. It changed the pathway through which implicit agency became moral accountability.", meta: ["N = 69", "Physical vs. virtual EMO", "SC-IAT before and after", "Moderation analysis"], role: { title: "I built a matched embodiment test around a moral question.", body: "As sole author and principal investigator, I developed the theoretical model, built and matched the physical and virtual interaction conditions, ran the study, analyzed the implicit and explicit measures, and wrote the manuscript.", tags: ["Sole author", "Embodied AI", "Experimental system", "SC-IAT", "R / moderation"] }, nodes: [
      { key: "intro", label: "01 · Intro", title: "A body may change not what we say about AI, but how its actions register before reflection.", paragraphs: ["People readily deny that current AI has a mind, yet still respond to a robot's gaze, movement, and proximity. I wanted to test whether physical co-presence changes implicit mind perception—and whether that change becomes moral attribution.", "The focus was not whether robots deserve moral status in the abstract, but how embodiment alters the psychological route to that judgment."], figures: [{ src: "assets/papers/embodiment-conditions.png", alt: "Physical robot and matched virtual avatar study conditions", caption: "The two EMO agents were matched in appearance, voice, and command set as closely as possible." }] },
      { key: "lit", label: "02 · Short lit review", title: "Agency and Experience imply different kinds of moral standing.", paragraphs: ["Mind-perception research distinguishes Agency—the capacity to plan and act—from Experience—the capacity to feel. Moral psychology links Agency to responsibility and Experience to deserving protection.", "Embodiment research often measures presence or liking. This study instead asked whether a body changes the coupling between implicit mind perception and moral judgment." ] },
      { key: "method", label: "03 · Method", title: "The same ten-minute encounter, located either in shared space or inside a browser.", paragraphs: ["Sixty-nine participants interacted with a physical desktop EMO robot (n = 36) or a matched browser-based avatar (n = 33). Both conditions used the same voice and command categories; the physical condition added touch and spatial co-presence, while the virtual condition used hover, click, drag, and webcam interaction.", "Participants completed Agency and Experience SC-IATs before and after the interaction, followed by Moral Agency, Moral Patiency, and explicit mind ratings."], stats: [{ value: "69", label: "participants" }, { value: "10 min", label: "matched interaction" }, { value: "2 × 2", label: "pre/post × embodiment" }], figures: [{ src: "assets/papers/embodiment-conditions.png", alt: "Physical and virtual study conditions", caption: "The comparison isolates the presence of a body in shared physical space." }] },
      { key: "results", label: "04 · Results", title: "Physical presence increased implicit Experience and made Agency morally diagnostic.", paragraphs: ["Physical embodiment increased implicit Experience (g = .63, p = .012), while implicit Agency did not change (p = .901). Explicit mind and moral ratings did not differ between conditions.", "The critical moderation was relational: change in implicit Agency predicted Moral Agency in the physical condition (β = .43, p = .011) but not the virtual condition (β = −.10, p = .575). The interaction was significant (β = .525, p = .031)."], stats: [{ value: ".63", label: "implicit Experience g" }, { value: ".525", label: "Agency × physical β" }, { value: "n.s.", label: "explicit-rating difference" }], figures: [{ src: "assets/papers/embodiment-implicit.png", alt: "Implicit Agency and Experience change by embodiment", caption: "Embodiment selectively shifted implicit Experience." }, { src: "assets/papers/embodiment-moderation.png", alt: "Physical co-presence moderation of Agency to Moral Agency", caption: "Agency became morally predictive only when the AI shared physical space." }] },
      { key: "discussion", label: "05 · Discussion", title: "A body can make local agency feel real while hiding the larger system behind it.", paragraphs: ["Embodiment does not simply make an AI more moral. It makes some perceived capacities more interpretable as responsibility. That distinction helps reconcile unchanged explicit ratings with a changed implicit-to-moral pathway.", "For HRI, the policy implication is accountability scaffolding: interfaces should make visible when an embodied agent is acting locally, following a remote model, or executing a developer's decision. A convincing body should not become a convenient mask for distributed responsibility." ] },
    ] }
  },
  screenx: {
    eyebrow: "Journal article · 2025", title: "What Makes Audiences Pay More for Immersive Cinema?", summary: "A concise conjoint study of which ScreenX attributes create preference and willingness to pay.", role: "Co-author. Contributed to study design, quantitative modeling, segmentation, and interpretation.", methods: "N = 400; discrete choice experiment; multinomial logit; WTP confidence intervals; K-means; R.", finding: "Genre was most influential, but four audience segments showed that premium value depends on the fit among content, timing, and sensory design.", paper: "https://www.dbpia.co.kr/journal/articleDetail?nodeId=NODE12717030", page: "research/screenx.html",
    researchMap: { question: "What exactly makes an immersive cinema experience worth paying more for?", answer: "There is no single premium feature: value emerges from the fit between genre, timing, sensory intensity, and audience segment.", meta: ["N = 400", "Discrete choice experiment", "Multinomial logit", "K-means segments"], role: { title: "I helped translate audience choices into design and pricing evidence.", body: "As co-author, I contributed to the research design, quantitative modeling, clustering, and interpretation of what different audience groups value.", tags: ["Conjoint design", "WTP modeling", "Audience segmentation", "R"] }, nodes: [
      { key: "intro", label: "01 · Question", title: "Immersion is sold as a premium, but audiences may be paying for different things.", paragraphs: ["ScreenX combines expanded visual space with content and scheduling choices. We asked which attributes actually drive preference and how much additional value viewers assign to them." ] },
      { key: "method", label: "02 · Method", title: "Choice tasks reveal tradeoffs that ratings often hide.", paragraphs: ["Four hundred adults completed a discrete choice experiment. We estimated a multinomial logit model, calculated willingness-to-pay confidence intervals with the delta method, and used K-means clustering to identify audience segments."], stats: [{ value: "400", label: "participants" }, { value: "33.2%", label: "genre importance" }, { value: "4", label: "audience segments" }] },
      { key: "results", label: "03 · Results", title: "Genre mattered most overall, but the average concealed four distinct audiences.", paragraphs: ["Genre carried the highest relative importance (33.2%). Segment analysis showed that premium value depended on different combinations of content, viewing time, and sensory dimensions rather than one universally preferred configuration." ] },
      { key: "discussion", label: "04 · Implication", title: "Immersive cinema should be configured by audience fit, not by maximal intensity.", paragraphs: ["The study offers a practical way to connect experience design with programming and pricing. For HCI, it also shows how choice modeling can reveal heterogeneous preferences that a single satisfaction score would flatten." ] },
    ] }
  },
};
